openapi: 3.1.0
info:
  contact:
    email: blah+oapicf@cliffano.com
    name: OpenAPI Clients Factory
    url: https://github.com/oapicf/openapi-ipify
  description: "OpenAPI client for ipify, a simple public IP address API"
  license:
    name: MIT
  title: openapi-ipify
  version: 5.3.1-pre.0
servers:
- url: https://api64.ipify.org
paths:
  /:
    get:
      operationId: getIp
      parameters:
      - description: Response format
        explode: true
        in: query
        name: format
        required: false
        schema:
          enum:
          - json
          - jsonp
          type: string
        style: form
      - description: JSONP callback function name
        explode: true
        in: query
        name: callback
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              example: 192.168.1.1
              schema:
                type: string
            application/json:
              schema:
                $ref: "#/components/schemas/getIp_200_response"
            application/javascript:
              example: "callback({\"ip\":\"192.168.1.1\"})"
              schema:
                type: string
          description: Your public IP address
      summary: Get your public IP address
components:
  schemas:
    getIp_200_response:
      example:
        ip: 192.168.1.1
      properties:
        ip:
          type: string
